script: 'apt update;
  apt install -y git;
  git clone https://github.com/llaske/sugarizer;
  git clone https://github.com/llaske/sugarizer-server;
  curl -fsSL https://get.docker.com/ | sh;
  cd sugarizer-server;
  docker compose up -d'
